version: '3.8'

networks:
  tech-network:
    driver: bridge

services:
  springboot-app:
    image: tech:latest
    build: .
    ports:
      - "6443:2002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tech-mysql-db:3306/CyfrifProTech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./keystore.p12:/tech/keystore.p12  # Moved outside environment
    depends_on:
      tech-mysql-db:
        condition: service_healthy
    networks:
      - tech-network

  tech-mysql-db:
    image: mysql:8
    container_name: tech-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CyfrifProTech
    ports:
      - "3302:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:
